spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopping_user?characterEncoding=utf-8
    username: root
    password: password
  jpa:
    show-sql: true
    database: mysql

server:
  port: 8082